name: Commit
on: push

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - uses: actions/setup-java@v2
          with:
            distribution: 'temurin'
            java-version: 8

        - name: Run tests
          uses: extenda/actions/maven@v0
          with:
            args: verify

        - name: Scan with SonarCloud
          uses: extenda/actions/sonar-scanner@v0
          with:
            sonar-host: https://sonarcloud.io
            sonar-scanner: maven
            main-branch: master

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Create release
        uses: extenda/actions/conventional-release@v0
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build release
        uses: extenda/actions/maven@v0
        with:
          args: deploy -DskipTests
          version: ${{ steps.release.outputs.version }}
